export const LOGIN = 'USER_LOGIN';
export const LOGOUT = 'USER_LOGOUT';
export const UPDATE_EMAIL = 'USER_UPDATE_EMAIL';
export const UPDATE_PASSWORD = 'USER_UPDATE_PASSWORD';
export const UPDATE_PASSWORD_CONFIRMATION = 'USER_UPDATE_PASSWORD_CONFIRMATION';