export const SET_SETTINGS_MUSIC = 'SET_SETTINGS_MUSIC';
export const SET_SETTINGS_SOUND = 'SET_SETTINGS_SOUND';
export const SET_SETTINGS_VIBRATION = 'SET_SETTINGS_VIBRATION';
export const SET_SETTINGS_VOLUME = 'SET_SETTINGS_VOLUME';
