// This file is automatically generated by vscode-react-native@0.2.3
// Please do not modify it manually. All changes will be lost.
var React = require('react');
var {Component} = React;

var ReactNative = require('react-native');
var {AppRegistry} = ReactNative;

var entryPoint = require("../index.android.js");

AppRegistry.registerRunnable('main', (appParameters) => {
    AppRegistry.runApplication('DiceRollerBeta1', appParameters);
});